name: fitness_tracker_gauge
description: Aplikasi visualisasi data fitness murid menggunakan Radial Gauge.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Package utama untuk membuat Radial Gauge
  syncfusion_flutter_gauges: ^21.2.9
  syncfusion_flutter_charts: ^24.2.7
  # Standar ikon untuk Flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter untuk memastikan kualitas kode Anda tetap rapi
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Daftarkan asset Anda di bawah ini
  assets:
    - assets/atlet_data.json

