name: Preview UI via GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      # Membuat hasil build web dengan nama repositori yang benar
      - name: Build Web
        run: flutter build web --release --base-href "/blajar-fultter/"

      # TRICK: Mengirim hasil build langsung ke branch gh-pages
      - name: Deploy ke Branch gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages # Hasil web ditaruh di sini
