name: Flutter Web Preview

on:
  push:
    branches: [ "main" ] # Otomatis update web setiap Anda push ke branch main

# Memberikan izin ke token GitHub untuk mempublikasikan website halaman (GitHub Pages)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode terbaru dari repository Anda
      - uses: actions/checkout@v4

      # 2. Setup Flutter SDK di Server GitHub
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Bersihkan cache dan ambil dependensi
      - name: Clean and Install dependencies
        run: |
          flutter clean
          flutter pub get

      # 4. Proses Kompilasi menjadi file Web HTML/JS (Bukan APK)
      - name: Build Flutter Web
        run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      # 5. Mengunggah hasil kompilasi web ke server internal GitHub
      - name: Upload Web Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      # 6. Menayangkan langsung hasil kompilasi ke internet (Deploy)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
